int BLOCK_RATIO = 10;
int BLOCK_SPACING = 1;
int BLOCK_OFFSET = BLOCK_RATIO / 2;
int BLOCK_SIZE = BLOCK_RATIO - BLOCK_SPACING;

int PAN_SPEED = 10;

int UI_SCALE = 75;
int UI_BORDER = 30;
int UI_SPACING = 20;
